/*Table structure for table `province` */

DROP TABLE IF EXISTS `province`;

CREATE TABLE `province` (
  `sigla` char(2) NOT NULL,
  `nome` varchar(50) NOT NULL,
  PRIMARY KEY (`sigla`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `province` */

insert  into `province`(`sigla`,`nome`) values

("AO","Aosta"),
("AR","Arezzo"),
("AP","Ascoli Piceno"),
("AT","Asti"),
("AV","Avellino"),
("BA","Bari"),
("BL","Belluno"),
("BN","Benevento"),
("BG","Bergamo"),
("BI","Biella"),
("BO","Bologna"),
("BZ","Bolzano"),
("BS","Brescia"),
("BR","Brindisi"),
("CA","Cagliari"),
("CL","Caltanissetta"),
("CB","Campobasso"),
("CE","Caserta"),
("CT","Catania"),
("CZ","Catanzaro"),
("CH","Chieti"),
("CO","Como"),
("CS","Cosenza"),
("CR","Cremona"),
("KR","Crotone"),
("CN","Cuneo"),
("EN","Enna"),
("FE","Ferrara"),
("FI","Firenze"),
("FG","Foggia"),
("FO","Forli'-Cesena"),
("FR","Frosinone"),
("GE","Genova"),
("GO","Gorizia"),
("GR","Grosseto"),
("IM","Imperia"),
("IS","Isernia"),
("SP","La Spezia"),
("AQ","L'Aquila"),
("LT","Latina"),
("LE","Lecce"),
("LC","Lecco"),
("LI","Livorno"),
("LO","Lodi"),
("LU","Lucca"),
("MC","Macerata"),
("MN","Mantova"),
("MS","Massa-Carrara"),
("MT","Matera"),
("ME","Messina"),
("MI","Milano"),
("MO","Modena"),
("NA","Napoli"),
("NO","Novara"),
("NU","Nuoro"),
("OR","Oristano"),
("PD","Padova"),
("PA","Palermo"),
("PR","Parma"),
("PV","Pavia"),
("PG","Perugia"),
("PS","Pesaro e Urbino"),
("PE","Pescara"),
("PC","Piacenza"),
("PI","Pisa"),
("PT","Pistoia"),
("PN","Pordenone"),
("PZ","Potenza"),
("PO","Prato"),
("RG","Ragusa"),
("RA","Ravenna"),
("RC","Reggio di Calabria"),
("RE","Reggio nell'Emilia"),
("RI","Rieti"),
("RN","Rimini"),
("RM","Roma"),
("RO","Rovigo"),
("SA","Salerno"),
("SS","Sassari"),
("SV","Savona"),
("SI","Siena"),
("SR","Siracusa"),
("SO","Sondrio"),
("TA","Taranto"),
("TE","Teramo"),
("TR","Terni"),
("TO","Torino"),
("TP","Trapani"),
("TN","Trento"),
("TV","Treviso"),
("TS","Trieste"),
("UD","Udine"),
("VA","Varese"),
("VE","Venezia"),
("VB","Verbano-Cusio-Ossola"),
("VC","Vercelli"),
("VR","Verona"),
("VV","Vibo Valentia"),
("VI","Vicenza"),
("VT","Viterbo")
